// Authoritative Phase 7A semantic registry. No scoring or profile inference.
export const EMPLOYMENT_INTELLIGENCE_VERSION = 'employment-intelligence-v1'
// No approved project disclosure threshold exists. Do not substitute a legal threshold.
export const MIN_SENSITIVE_AGGREGATE_COUNT = null

// ID, name, measure, grain, source/numerator, denominator, date basis, dimensions,
// limitation, availability, privacy, event scope, data-quality classification.
const definitions = [
  ["unique_participants","Registered persons","count","person","participants.id",null,"current_snapshot",[],"Includes people without a jobseeker profile.","available","government_aggregate",false,false],
  ["unique_jobseekers","Registered jobseekers","count","person","participants.id JOIN jobseeker_profiles.participant_id",null,"current_snapshot",[],"Registration is not current labor-force participation.","available","government_aggregate",false,false],
  ["jobseekers_registered","Jobseekers by person registration date","count","person","participants.created_at; current jobseeker_profiles membership",null,"participants.created_at",[],"Current profile membership; deleted profiles cannot be reconstructed.","available","government_aggregate",false,false],
  ["active_jobseekers","Active jobseekers","count","person","No activity/active flag or approved recency definition",null,"unavailable",[],"Requires an approved activity definition.","unavailable","government_aggregate",false,false],
  ["unique_vacancy_definitions","Distinct job definitions","count","vacancy_definition","vacancy_definitions.id",null,"current_snapshot",[],"Reusable definitions; not openings.","available","government_aggregate",false,false],
  ["active_vacancies","Active job definitions","count","vacancy_definition","vacancy_definitions.id WHERE is_active = true",null,"current_snapshot",[],"Active flag does not establish an unexpired event offering.","available","government_aggregate",false,false],
  ["vacancies_posted","Job definitions created","count","vacancy_definition","vacancy_definitions.id",null,"vacancy_definitions.created_at",[],"Creation count; not occupied positions.","available","government_aggregate",false,false],
  ["event_vacancy_offerings","Event job offerings","count","event_vacancy","event_vacancies.id JOIN events",null,"events.event_date",[],"One definition may occur at multiple events; slots are not summed.","available","government_aggregate",true,false],
  ["jobseekers_by_preferred_occupation","Explicit occupation interest","count","person_per_occupation","jobseeker_occupation_preferences.jobseeker_profile_id, occupation_id",null,"current_snapshot",["occupation"],"Confirmed canonical preferences only; multiple categories per person.","available","government_aggregate",false,false],
  ["jobseekers_by_preferred_industry","Explicit industry interest","count","person_per_industry","jobseeker_industry_preferences.jobseeker_profile_id, industry_id",null,"current_snapshot",["industry"],"History and legacy free text excluded; multiple categories per person.","available","government_aggregate",false,false],
  ["skills_supply","Declared canonical skill supply","count","person_per_skill","jobseeker_skills.jobseeker_profile_id, skill_id",null,"current_snapshot",["skill"],"Declared, not independently verified proficiency; human-confirmed AI rows only.","available","government_aggregate",false,false],
  ["skills_demand_required","Required skill demand","count","vacancy_definition_per_skill","vacancy_skills WHERE importance = required JOIN active vacancy_definitions",null,"current_snapshot",["skill"],"Distinct definitions; not opening count.","available","government_aggregate",false,false],
  ["skills_demand_preferred","Preferred skill demand","count","vacancy_definition_per_skill","vacancy_skills WHERE importance = preferred JOIN active vacancy_definitions",null,"current_snapshot",["skill"],"Kept separate from required demand.","available","government_aggregate",false,false],
  ["skill_gap","Observed skill supply-demand ratio","ratio","skill","skills_supply","skills_demand_required","current_snapshot",["skill"],"System-wide current registered profiles versus active definitions; no geographic/time cohort filter, shortage inference, subtraction, or opening estimate.","available","government_aggregate",false,false],
  ["vacancies_by_occupation","Active jobs by occupation","count","vacancy_definition_per_occupation","vacancy_definitions.occupation_id",null,"current_snapshot",["occupation"],"Null canonical occupation excluded and measured in data quality.","available","government_aggregate",false,false],
  ["vacancies_by_industry","Active jobs by industry","count","vacancy_definition_per_industry","vacancy_definitions.industry_id",null,"current_snapshot",["industry"],"Canonical vacancy industry; not employer free text.","available","government_aggregate",false,false],
  ["vacancies_by_employment_type","Active jobs by employment type","count","vacancy_definition_per_employment_type","vacancy_definitions.employment_type_id",null,"current_snapshot",["employment_type"],"Unknown canonical values excluded.","available","government_aggregate",false,false],
  ["vacancies_by_work_arrangement","Active jobs by work arrangement","count","vacancy_definition_per_work_arrangement","vacancy_definitions.work_arrangement_id",null,"current_snapshot",["work_arrangement"],"Unknown canonical values excluded.","available","government_aggregate",false,false],
  ["jobseekers_by_employment_type","Employment-type preferences","count","person_per_employment_type","jobseeker_employment_type_preferences",null,"current_snapshot",["employment_type"],"Explicit canonical preferences; multiple categories possible.","available","government_aggregate",false,false],
  ["jobseekers_by_work_arrangement","Work-arrangement preferences","count","person_per_work_arrangement","jobseeker_work_arrangement_preferences",null,"current_snapshot",["work_arrangement"],"Explicit canonical preferences; multiple categories possible.","available","government_aggregate",false,false],
  ["candidate_interest_count","Recorded event interests","count","participation_vacancy","participation_vacancies.participation_id, event_vacancy_id",null,"participation_vacancies.created_at",[],"Interest is not a formal application.","available","government_aggregate",true,false],
  ["applications_submitted","Formal applications submitted","count","application","applications.id",null,"applications.applied_at",[],"Includes later withdrawn/rejected applications; excludes interest-only records.","available","government_aggregate",true,false],
  ["interviews_recorded","Recorded interview results","count","interview","interview_logs.id",null,"interview_logs.interview_date",[],"Result records; multiple results per application possible, application link nullable.","available","government_aggregate",true,false],
  ["interviews_completed","Completed interviews","count","interview","No completed/scheduled lifecycle field",null,"unavailable",[],"Recorded result is not a modeled completion lifecycle.","unavailable","government_aggregate",false,false],
  ["hires_recorded","Confirmed recorded hires","count","application","Latest employment_outcomes row per application: hired, verified_by, verification_date and hired_at present",null,"employment_outcomes.hired_at",[],"Latest record by created_at,id governs; HOTS excluded; corrections/deletions alter historical totals.","available","government_aggregate",true,false],
  ["application_to_recorded_interview_rate","Application to recorded interview rate","rate","application_cohort","Applications with linked interview_logs.application_id","All submitted applications in applied_at cohort","applications.applied_at",[],"Observed to current query date, not a mature cohort estimate; unlinked interviews excluded.","available","government_aggregate",true,false],
  ["application_to_confirmed_hire_rate","Application to confirmed hire rate","rate","application_cohort","Applications with latest confirmed hire outcome","All submitted applications in applied_at cohort","applications.applied_at",[],"Observed to current query date; incomplete/unverified/pending outcomes excluded from numerator.","available","government_aggregate",true,false],
  ["recorded_interview_to_confirmed_hire_rate","Recorded interview to confirmed hire rate","rate","application_cohort","Applications with linked interview and latest confirmed hire","Submitted cohort applications with linked interview","applications.applied_at",[],"Application grain prevents duplicate interview logs inflating denominator; no claim of interview completion.","available","government_aggregate",true,false],
  ["event_participation_count","Event registrations","count","event_participation","event_participations.id",null,"events.event_date",[],"Registration is not attendance; cancelled events retained as recorded activity.","available","government_aggregate",true,false],
  ["event_unique_participants","Distinct event participants","count","person","event_participations.participant_id",null,"events.event_date",[],"Distinct across selected event cohort; sum of event counts is not unique persons.","available","government_aggregate",true,false],
  ["event_application_count","Event applications","count","application","applications.id -> event_vacancies.event_id",null,"events.event_date",[],"Attributed to offering event; not application submission date.","available","government_aggregate",true,false],
  ["event_interview_count","Event interview records","count","interview","interview_logs.id, event_id",null,"events.event_date",[],"Attributed by interview event_id; not completion lifecycle.","available","government_aggregate",true,false],
  ["event_hire_count","Event confirmed hires","count","application","Confirmed latest outcome -> applications -> event_vacancies.event_id",null,"events.event_date",[],"Offering-event attribution; later verified hires observed at query time.","available","government_aggregate",true,false],
  ["employer_participation_count","Employer event registrations","count","employer_event_participation","employer_event_participations WHERE status <> cancelled",null,"events.event_date",[],"Registered/checked_in/no_show; does not imply attendance.","available","government_aggregate",true,false],
  ["event_employers_checked_in","Employers checked in","count","employer_event_participation","employer_event_participations WHERE status = checked_in",null,"events.event_date",[],"Recorded check-in, no employer quality score.","available","government_aggregate",true,false],
  ["active_approved_employers","Active approved employers","count","employer","employers.id WHERE is_active AND registration_status = approved",null,"current_snapshot",[],"Administrative approval and active state, not hiring quality.","available","government_aggregate",false,false],
  ["employers_with_vacancies","Employers with recorded jobs","count","employer","Distinct nonnull vacancy_definitions.employer_id",null,"current_snapshot",[],"Legacy unlinked jobs excluded; no ranking.","available","government_aggregate",false,false],
  ["follow_ups_completed","Completed follow-ups","count","follow_up","follow_ups.id WHERE status = completed",null,"follow_ups.completed_date",[],"No retention rate without verified still-employed and cohort methodology.","available","government_aggregate",false,false],
  ["jobseekers_without_occupation_preference","Missing confirmed occupation preference","count","person","Profiles without confirmed jobseeker_occupation_preferences",null,"current_snapshot",[],"Missing information, not lack of occupational intent.","available","government_aggregate",false,true],
  ["jobseekers_without_skills","Missing confirmed canonical skills","count","person","Profiles without confirmed jobseeker_skills",null,"current_snapshot",[],"Unknown supply, not no skills.","available","government_aggregate",false,true],
  ["vacancies_without_canonical_occupation","Missing canonical job occupation","count","vacancy_definition","Active vacancy_definitions WHERE occupation_id IS NULL",null,"current_snapshot",[],"No inference from position text.","available","government_aggregate",false,true],
  ["vacancies_without_salary","Missing usable salary range","count","vacancy_definition","Active vacancy_definitions without usable structured salary bounds/currency/period",null,"current_snapshot",[],"Negotiable/text-only/invalid range counted as incomplete.","available","government_aggregate",false,true],
  ["applications_without_final_outcome","Applications without final recorded outcome","count","application_cohort","Applications with absent or latest pending outcome",null,"applications.applied_at",[],"Final outcome completeness is distinct from hire verification.","available","government_aggregate",true,true],
  ["occupation_preference_coverage","Occupation preference coverage","percent","person","Profiles with confirmed canonical occupation preference","All current jobseeker profiles","current_snapshot",[],"Data quality percentage, not an outcome.","available","government_aggregate",false,true],
  ["skill_coverage","Canonical skill coverage","percent","person","Profiles with confirmed canonical skill","All current jobseeker profiles","current_snapshot",[],"Data quality; declaration is not verified proficiency.","available","government_aggregate",false,true],
  ["vacancy_occupation_coverage","Job occupation coverage","percent","vacancy_definition","Active jobs with nonnull canonical occupation","All active job definitions","current_snapshot",[],"Data quality, no title inference.","available","government_aggregate",false,true],
  ["vacancy_salary_coverage","Job salary coverage","percent","vacancy_definition","Active jobs with usable structured salary range","All active job definitions","current_snapshot",[],"Does not establish comparability across periods/currencies.","available","government_aggregate",false,true],
  ["vacancy_required_skill_coverage","Required skill coverage","percent","vacancy_definition","Active jobs with at least one required vacancy_skills row","All active job definitions","current_snapshot",[],"Missing requirement may be intentional, not a qualification gap.","available","government_aggregate",false,true],
  ["application_outcome_coverage","Final outcome coverage","percent","application_cohort","Applications whose latest outcome is final","All applications in applied_at cohort","applications.applied_at",[],"Recorded final outcome, including non-hire, not verified hire coverage.","available","government_aggregate",true,true],
  ["jobseekers_by_residence","Jobseekers by residence","count","person","jobseeker_profiles.province, municipality_city; barangay excluded",null,"current_snapshot",["residence_municipality"],"Free text needs validated geography mapping and disclosure policy before output.","unavailable","government_aggregate",false,false],
  ["jobseekers_by_preferred_location","Preferred work geography","count","person_per_location","jobseeker_location_preferences.region, province, municipality_city",null,"current_snapshot",["preferred_work_municipality"],"Distinct from residence; canonical geography and disclosure review pending.","unavailable","government_aggregate",false,false],
  ["vacancies_by_work_location","Vacancy work geography","count","vacancy_definition","vacancy_definitions.province, municipality_city",null,"current_snapshot",["vacancy_work_municipality"],"Distinct from employer address/event location; canonical geography pending.","unavailable","government_aggregate",false,false],
  ["vacancy_salary_average","Average offered salary","average","vacancy_definition","vacancy_definitions.salary_min, salary_max, salary_currency, salary_period",null,"current_snapshot",[],"No agreed bound/midpoint normalization across currencies and pay periods.","unavailable","government_aggregate",false,false],
  ["jobseeker_salary_median","Median expected salary","median","person","jobseeker_profiles.desired_salary_min/max/currency/period",null,"current_snapshot",[],"No approved bound selection or period/currency normalization.","unavailable","government_aggregate",false,false],
  ["program_reach","Verified program reach","count","person_program","Ambiguous legacy metric. Program participation records now exist, but a single 'reach' number has no approved stage definition. Use stage-specific program metrics instead.",null,"unavailable",[],"Ambiguous legacy metric. Program participation records now exist, but a single 'reach' number has no approved stage definition. Use stage-specific program metrics instead.","unavailable","government_aggregate",false,false],
  ["program_referrals","Program referrals","count","transition","Effective reported and verified program_participation_events where stage=referred (correction-aware)",null,"program_participation_events.occurred_at",["program","program_cycle"],"Referral transition count by occurred_at date; corrections do not double-count.","available","government_aggregate",false,false],
  ["program_applications","Program applications","count","transition","Effective reported and verified program_participation_events where stage=applied (correction-aware)",null,"program_participation_events.occurred_at",["program","program_cycle"],"Application transition count; not all participants apply.","available","government_aggregate",false,false],
  ["program_enrollments","Program enrollments","count","transition","Effective reported and verified program_participation_events where stage=enrolled (correction-aware)",null,"program_participation_events.occurred_at",["program","program_cycle"],"Enrollment transition count by occurred_at date.","available","government_aggregate",false,false],
  ["program_starts","Program starts","count","transition","Effective reported and verified program_participation_events where stage=started (correction-aware)",null,"program_participation_events.occurred_at",["program","program_cycle"],"Program start transition count.","available","government_aggregate",false,false],
  ["program_completions","Program completions","count","transition","Effective reported and verified program_participation_events where stage=completed (correction-aware)",null,"program_participation_events.occurred_at",["program","program_cycle"],"Completion transition count; not employment placement count.","available","government_aggregate",false,false],
  ["program_withdrawals","Program withdrawals","count","transition","Effective reported and verified program_participation_events where stage=withdrawn (correction-aware)",null,"program_participation_events.occurred_at",["program","program_cycle"],"Withdrawal transition count.","available","government_aggregate",false,false],
  ["program_disqualifications","Program disqualifications","count","transition","Effective reported and verified program_participation_events where stage=disqualified (correction-aware)",null,"program_participation_events.occurred_at",["program","program_cycle"],"Disqualification transition count.","available","government_aggregate",false,false],
  ["unique_program_participants","Unique program participants","count","person","DISTINCT participant_id in program_participations within scope",null,"current_snapshot",["program","program_cycle"],"Distinct persons with any program participation record; current snapshot only, null/not_applicable for date ranges.","available","government_aggregate",false,false],
  ["program_participants_with_verified_employment","Participants with verified employment outcome","count","person","DISTINCT participant_id with valid verified effective employment-outcome link after program participation",null,"current_snapshot",["program","program_cycle"],"Employment observed after participation; current valid verified recruitment link; no causal claim; null/not_applicable for date ranges.","available","government_aggregate",false,false],
  ["special_sector_count","Restricted special-sector aggregates","count","person_sector","jobseeker_special_sectors; jobseeker_profiles structured classification flags",null,"current_snapshot",[],"All cells withheld pending approved small-cell and complementary suppression policy.","policy_pending","sensitive",false,false],
].map(([metric_id, name, measure, grain, source, denominator, date_basis, dimensions,
  limitation, status, privacy_classification, event_scope, is_data_quality]) => ({
  metric_id, name, description: name, measure, grain, source, numerator: source,
  denominator, date_basis, dimensions, limitations: [limitation], status,
  privacy_classification, event_scope, is_data_quality,
  minimum_aggregation_requirement: privacy_classification === 'sensitive'
    ? 'Policy approval pending; suppress all values'
    : 'Admin-only aggregate; no individual identifiers',
}))

function freeze(value) {
  if (value && typeof value === 'object') {
    Object.values(value).forEach(freeze)
    Object.freeze(value)
  }
  return value
}
export const EMPLOYMENT_INTELLIGENCE_METRICS = freeze(Object.fromEntries(definitions.map(metric => [metric.metric_id, metric])))
// This family has its own program/cycle aggregate contract. Registration is not activation.
export const PROGRAM_METRIC_IDS = Object.freeze([
  'program_referrals', 'program_applications', 'program_enrollments', 'program_starts',
  'program_completions', 'program_withdrawals', 'program_disqualifications',
  'unique_program_participants', 'program_participants_with_verified_employment',
])
export function getMetricDefinition(id) {
  if (!Object.hasOwn(EMPLOYMENT_INTELLIGENCE_METRICS, id)) throw new TypeError('Unknown employment intelligence metric')
  return EMPLOYMENT_INTELLIGENCE_METRICS[id]
}
